name: CI

on: [release]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish
      env:

      run: |
        echo Publishing to npm...
        yarn publish
